version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "80"

  serviceapi:
    image: ${DOCKER_REGISTRY-}serviceapi
    build:
      context: .
      dockerfile: ServiceAPI/Dockerfile
    ports:
      - "80"


  authenticationapi:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: AuthenticationAPI/Dockerfile
    ports:
      - "80" 

